development:
  adapter: postgresql
  encoding: unicode
  database: CHANGE_ME_development
  pool: 5
  username: dylanoshea
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: CHANGE_ME_test
  pool: 5
  username: dylanoshea
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: CHANGE_ME_production
  pool: 5
  username: dylanoshea
  password:
